services:
  app:
    build: ./docker/app
    container_name: app_edulabs
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api_edulabs
    ports:
      - "9010:9010"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db
      - minio
  nginx:
    image: nginx:alpine
    container_name: proxy_edulabs
    ports:
      - "8081:80"
    volumes:
      - ./docker/api/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api:/var/www/html
    depends_on:
      - api
  db:
    image: mysql:8.0
    container_name: mysql_edulabs
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
      MYSQL_USER: app
      MYSQL_PASSWORD: secure
    ports:
      - "3307:3306"
    volumes:
      - ./docker/tmp/db:/var/lib/mysql
  minio:
    image: minio/minio:latest
    container_name: minio_edulabs
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker/tmp/minio:/data
  init_minio:
    image: minio/mc:latest
    container_name: minio_init_edulabs
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      while ! mc alias set myminio http://minio:9000 minio minio12345; do
        echo 'Esperando que MinIO esté disponible...';
        sleep 5;
      done;
      echo 'MinIO está disponible, creando bucket...';
      mc mb myminio/prueba-edulabs;
      "
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345